logo_title: 安辰

style: white

favicon: /favicon.ico

menu:
  首页: /
  关于: /about
  标签: /tags/index.html
  分类: /categories
  归档: /archives
  运动: https://anchen.me/running_page

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: false
  appId: CmCti21ooOOIzFOhEyFkFvR0-gzGzoHsz
  appKey: FqiyUqbg7McKN2eG0MCewupf

highlight:
  enable: false